'use client';

import React from 'react';

export default function HeroSection() {
  const continuityItems = [
    {
      label: 'EVENT STATUS',
      value: 'Broadcasting Completed',
      variant: 'ready',
    },
    {
      label: 'RECORDING STATE',
      value: 'Capture Active (Sanctuary SRT Ingest)',
      variant: 'ready',
    },
    {
      label: 'REPLAY STATUS',
      value: 'Replay Pending Verification Gate',
      variant: 'warning',
    },
    {
      label: 'AUDIENCE ACCESS',
      value: 'Secure SAML Portal Only',
      variant: 'info',
    },
    {
      label: 'ACCESSIBILITY READY',
      value: 'Autogenerated Captions & Transcripts Processing',
      variant: 'warning',
    },
  ];

  const dotColor: Record<string, string> = {
    ready: 'bg-teal-400',
    warning: 'bg-orange-300',
    info: 'bg-blue-500',
  };

  return (
    <section
      className="relative w-full lg:h-[724px] overflow-hidden flex items-center bg-slate-950 text-white pt-33 sm:pt-20 lg:pt-39 pb-8 sm:pb-10 lg:pb-12 px-4 sm:px-6 lg:px-8 transition-colors duration-200 bg-cover bg-center bg-no-repeat"
      style={{
        backgroundImage: `linear-gradient(rgba(2, 6, 23, 0.15), rgba(2, 6, 23, 0.15)), url('/images/recording-replay-archive/hero-bg.jpg')`,
      }}
    >
      <div className="w-full max-w-7xl mx-auto flex flex-col lg:flex-row items-center justify-between gap-12 lg:gap-16 relative z-10">

        {/* Left Content Area */}
        <div className="w-full lg:max-w-[708px] flex flex-col justify-start items-start gap-6 sm:gap-8">

          {/* Category Tag */}
          <div className="px-3 py-1.5 rounded-full outline outline-1 outline-offset-[-1px] outline-blue-500 inline-flex items-center gap-2 bg-blue-500/10 backdrop-blur-sm">
            <span className="w-1.5 h-1.5 bg-blue-500 rounded-full" />
            <span className="text-blue-500 text-xs font-bold tracking-wider uppercase">
              Recording, Replay &amp; Archive
            </span>
          </div>

          {/* Headline */}
          <h1 className="text-slate-100 text-3xl sm:text-5xl lg:text-6xl font-bold leading-tight sm:leading-[1.15]">
            Decide what happens after the live moment.
          </h1>

          {/* Description */}
          <p className="text-slate-300 text-base sm:text-lg font-normal leading-relaxed">
            Plan recording, replay access, accessibility, corrections, archive, and retention as explicit event decisions - with clear ownership and honest states.
          </p>

          {/* Call to Action Buttons */}
          <div className="w-full sm:w-auto flex flex-col sm:flex-row items-stretch sm:items-center gap-4 pt-2">
            <button
              type="button"
              className="px-7 py-3.5 bg-gradient-to-r from-teal-400 to-blue-500 rounded-[10px] text-zinc-950 text-base font-bold hover:opacity-90 transition-opacity flex justify-center items-center"
            >
              Start your event brief
            </button>
            <button
              type="button"
              className="px-7 py-3.5 rounded-[10px] outline outline-1 outline-offset-[-1px] outline-gray-500 hover:outline-gray-400 bg-slate-900/40 backdrop-blur-sm text-slate-100 text-base font-medium transition-colors flex justify-center items-center"
            >
              Talk to an event expert
            </button>
          </div>

          <hr className="w-full border-t border-gray-800" />

          {/* Disclaimer */}
          <div className="w-full flex items-start gap-3">
            <span className="mt-0.5 shrink-0 w-4 h-4 rounded-full border border-blue-500 text-blue-500 text-[10px] font-bold flex items-center justify-center">
              i
            </span>
            <p className="text-slate-400 text-sm font-normal leading-relaxed">
              Nothing is recorded, published, retained, downloadable, or shared merely because an event is live. Exact post-event options are confirmed for the event and service scope.
            </p>
          </div>
        </div>

        {/* Right Continuity Card */}
        <div className="w-full lg:w-[520px] p-6 sm:p-7 bg-zinc-900/95 backdrop-blur-md rounded-[20px] shadow-2xl border border-gray-800 flex flex-col shrink-0">

          {/* Card Header */}
          <div className="w-full flex justify-between items-center pb-5">
            <div className="flex items-center gap-2">
              <span className="w-1.5 h-1.5 bg-teal-400 rounded-full" />
              <h2 className="text-slate-100 text-sm font-bold uppercase tracking-wide">
                Post-Event Continuity
              </h2>
            </div>
            <span className="text-slate-500 text-xs font-medium uppercase tracking-wide">
              v4.2.1 &middot; Armed
            </span>
          </div>

          <hr className="w-full border-t border-gray-800" />

          {/* Continuity Rows */}
          <div className="w-full flex flex-col">
            {continuityItems.map((item, index) => (
              <div
                key={index}
                className={`w-full flex justify-between items-center gap-4 py-4 ${
                  index !== continuityItems.length - 1 ? 'border-b border-gray-800' : ''
                }`}
              >
                <div className="flex flex-col gap-1">
                  <span className="text-slate-500 text-[11px] font-bold tracking-widest uppercase">
                    {item.label}
                  </span>
                  <span className="text-slate-100 text-sm sm:text-base font-medium">
                    {item.value}
                  </span>
                </div>
                <span className={`w-2 h-2 rounded-full shrink-0 ${dotColor[item.variant]}`} />
              </div>
            ))}
          </div>

        </div>

      </div>
    </section>
  );
}
