import React from 'react';
import Image from 'next/image';
import { Globe, Key, Building2, SlidersHorizontal, AppWindow } from 'lucide-react';

const audienceModels = [
  {
    title: 'Public / Open',
    desc: 'No viewer-specific restriction is applied. Access is determined purely by the publishing schedule and regional distribution limits of the media object.',
    badge: 'ANONYMOUS',
    icon: Globe,
  },
  {
    title: 'Invited / Verified',
    desc: 'Access is limited to viewers with a validated invitation code or secure token generated by the corporate directory.',
    badge: 'SECURE CODE',
    icon: Key,
  },
  {
    title: 'Organizational Tenant',
    desc: 'Viewers must authenticate against the corporate OIDC directory (Okta, Azure AD). Restricts playback strictly to internal employees.',
    badge: 'OIDC REQ',
    icon: Building2,
  },
  {
    title: 'Restricted / Entitled',
    desc: 'Enforces fine-grained viewer limits. Access is evaluated based on specific subscription tier, department code, or geography parameters.',
    badge: 'FINE-GRAINED',
    icon: SlidersHorizontal,
  },
  {
    title: 'Application-Mediated',
    desc: 'Decryption authority is delegated to a verified third-party partner app (e.g. customized corporate portals or integrated client dashboards).',
    badge: 'MUTUAL API',
    icon: AppWindow,
  },
];

export default function AudienceAccessModelsSection() {
  return (
    <section className="relative w-full bg-gray-950 text-white py-20 md:py-28 border-b border-gray-800 overflow-hidden">
      {/* Background Image */}
      <div className="absolute inset-0 pointer-events-none z-0">
        <Image
          src="/images/platform-access-control/bg (86).png"
          alt="Audience Models Background"
          fill
          className="object-cover opacity-60"
        />
        <div className="absolute inset-0 bg-gray-950/75" />
      </div>

      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        <div className="flex flex-col gap-3 mb-12">
          <h2 className="text-3xl md:text-4xl font-bold font-['Space_Grotesk'] text-white">
            Audience Access Models
          </h2>
          <p className="text-slate-400 text-base md:text-lg font-normal font-['Space_Grotesk'] max-w-3xl">
            Describe audience decisions without assuming every viewer has a corporate account.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-5">
          {audienceModels.map((model, idx) => {
            const Icon = model.icon;
            return (
              <div
                key={idx}
                className="p-6 bg-gray-900/80 rounded-xl border border-gray-800 backdrop-blur-sm flex flex-col justify-between gap-5 hover:border-teal-400/40 transition-colors"
              >
                <div className="flex flex-col gap-4">
                  <div className="size-10 bg-teal-400/10 rounded-lg border border-teal-400/25 flex items-center justify-center text-teal-400 shrink-0">
                    <Icon className="size-5" />
                  </div>
                  <div className="flex flex-col gap-2">
                    <h3 className="text-white text-base font-bold font-['Space_Grotesk']">
                      {model.title}
                    </h3>
                    <p className="text-slate-400 text-xs font-normal font-['Inter'] leading-relaxed">
                      {model.desc}
                    </p>
                  </div>
                </div>

                <div className="px-2 py-0.5 bg-teal-400/10 rounded text-[10px] font-bold font-['IBM_Plex_Mono'] text-teal-400 inline-block self-start">
                  {model.badge}
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
